# Generated by Django 5.0.3 on 2024-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_altura_customuser_genero_customuser_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
