# Generated by Django 5.0.3 on 2024-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('calorias_default', models.FloatField()),
                ('eet', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='foodlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=1000)),
                ('Energia', models.IntegerField()),
                ('Proteina', models.FloatField()),
                ('Carbohidratos', models.FloatField()),
                ('Azucares', models.FloatField()),
                ('Fibra_total_dietetica', models.FloatField()),
                ('Grasa_total', models.FloatField()),
                ('Acidos_grasos_saturados', models.FloatField()),
                ('Acidos_grasos_monoinsaturados', models.FloatField()),
                ('Acidos_grasos_poliinsaturados', models.FloatField()),
                ('Colesterol', models.FloatField()),
                ('Vitamina_B6', models.FloatField()),
                ('Vitamina_C', models.FloatField()),
                ('Vitamina_K', models.FloatField()),
                ('Calcio', models.FloatField()),
                ('Fosforo', models.FloatField()),
                ('Magnesio', models.FloatField()),
                ('Hierro', models.FloatField()),
                ('Zinc', models.FloatField()),
                ('Potasio', models.FloatField()),
                ('Sodio', models.FloatField()),
                ('Cafeina', models.FloatField()),
                ('Alcohol', models.FloatField()),
                ('Agua', models.FloatField()),
            ],
        ),
    ]
