# Generated by Django 5.0.3 on 2024-05-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_alter_foodlist_acidos_grasos_monoinsaturados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividades',
            old_name='calorias_default',
            new_name='calorias',
        ),
    ]
